#!/usr/bin/env bash
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1n_data_normal.pkl static/t1n_label_normal.pkl static/t1n_cluster_normal.pkl --restore models/max_model_trn_normal.ckpt --save predictions/t1n_label_normal_cluster.pkl predictions/t1n_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1l_data_normal.pkl static/t1l_label_normal.pkl static/t1l_cluster_normal.pkl --restore models/max_model_trl_normal.ckpt --save predictions/t1l_label_normal_cluster.pkl predictions/t1l_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1r_data_normal.pkl static/t1r_label_normal.pkl static/t1r_cluster_normal.pkl --restore models/max_model_trr_normal.ckpt --save predictions/t1r_label_normal_cluster.pkl predictions/t1r_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1s_data_normal.pkl static/t1s_label_normal.pkl static/t1s_cluster_normal.pkl --restore models/max_model_trs_normal.ckpt --save predictions/t1s_label_normal_cluster.pkl predictions/t1s_predict_normal_cluster.pkl

python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1n_data_bass.pkl static/t1n_label_bass.pkl static/t1n_cluster_bass.pkl --restore models/max_model_trn_bass.ckpt --save predictions/t1n_label_bass_cluster.pkl predictions/t1n_predict_bass_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1n_data_drums.pkl static/t1n_label_drums.pkl static/t1n_cluster_drums.pkl --restore models/max_model_trn_drums.ckpt --save predictions/t1n_label_drums_cluster.pkl predictions/t1n_predict_drums_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1n_data_melody.pkl static/t1n_label_melody.pkl static/t1n_cluster_melody.pkl --restore models/max_model_trn_melody.ckpt --save predictions/t1n_label_melody_cluster.pkl predictions/t1n_predict_melody_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t1n_data_other.pkl static/t1n_label_other.pkl static/t1n_cluster_other.pkl --restore models/max_model_trn_other.ckpt --save predictions/t1n_label_other_cluster.pkl predictions/t1n_predict_other_cluster.pkl


python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2n_data_normal.pkl static/t2n_label_normal.pkl static/t2n_cluster_normal.pkl --restore models/max_model_trn_normal.ckpt --save predictions/t2n_label_normal_cluster.pkl predictions/t2n_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2l_data_normal.pkl static/t2l_label_normal.pkl static/t2l_cluster_normal.pkl --restore models/max_model_trl_normal.ckpt --save predictions/t2l_label_normal_cluster.pkl predictions/t2l_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2r_data_normal.pkl static/t2r_label_normal.pkl static/t2r_cluster_normal.pkl --restore models/max_model_trr_normal.ckpt --save predictions/t2r_label_normal_cluster.pkl predictions/t2r_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2s_data_normal.pkl static/t2s_label_normal.pkl static/t2s_cluster_normal.pkl --restore models/max_model_trs_normal.ckpt --save predictions/t2s_label_normal_cluster.pkl predictions/t2s_predict_normal_cluster.pkl

python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2n_data_bass.pkl static/t2n_label_bass.pkl static/t2n_cluster_bass.pkl --restore models/max_model_trn_bass.ckpt --save predictions/t2n_label_bass_cluster.pkl predictions/t2n_predict_bass_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2n_data_drums.pkl static/t2n_label_drums.pkl static/t2n_cluster_drums.pkl --restore models/max_model_trn_drums.ckpt --save predictions/t2n_label_drums_cluster.pkl predictions/t2n_predict_drums_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2n_data_melody.pkl static/t2n_label_melody.pkl static/t2n_cluster_melody.pkl --restore models/max_model_trn_melody.ckpt --save predictions/t2n_label_melody_cluster.pkl predictions/t2n_predict_melody_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t2n_data_other.pkl static/t2n_label_other.pkl static/t2n_cluster_other.pkl --restore models/max_model_trn_other.ckpt --save predictions/t2n_label_other_cluster.pkl predictions/t2n_predict_other_cluster.pkl


python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3n_data_normal.pkl static/t3n_label_normal.pkl static/t3n_cluster_normal.pkl --restore models/max_model_trn_normal.ckpt --save predictions/t3n_label_normal_cluster.pkl predictions/t3n_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3l_data_normal.pkl static/t3l_label_normal.pkl static/t3l_cluster_normal.pkl --restore models/max_model_trl_normal.ckpt --save predictions/t3l_label_normal_cluster.pkl predictions/t3l_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3r_data_normal.pkl static/t3r_label_normal.pkl static/t3r_cluster_normal.pkl --restore models/max_model_trr_normal.ckpt --save predictions/t3r_label_normal_cluster.pkl predictions/t3r_predict_normal_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3s_data_normal.pkl static/t3s_label_normal.pkl static/t3s_cluster_normal.pkl --restore models/max_model_trs_normal.ckpt --save predictions/t3s_label_normal_cluster.pkl predictions/t3s_predict_normal_cluster.pkl

python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3n_data_bass.pkl static/t3n_label_bass.pkl static/t3n_cluster_bass.pkl --restore models/max_model_trn_bass.ckpt --save predictions/t3n_label_bass_cluster.pkl predictions/t3n_predict_bass_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3n_data_drums.pkl static/t3n_label_drums.pkl static/t3n_cluster_drums.pkl --restore models/max_model_trn_drums.ckpt --save predictions/t3n_label_drums_cluster.pkl predictions/t3n_predict_drums_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3n_data_melody.pkl static/t3n_label_melody.pkl static/t3n_cluster_melody.pkl --restore models/max_model_trn_melody.ckpt --save predictions/t3n_label_melody_cluster.pkl predictions/t3n_predict_melody_cluster.pkl
python3 cluster.py --hidden 256 --num_classes 11 --batch_size 256 --seq_length 49 --seq_dim 13 --num_layers 2 --lr 0.003 --decay 0.97 --data_set_load static/t3n_data_other.pkl static/t3n_label_other.pkl static/t3n_cluster_other.pkl --restore models/max_model_trn_other.ckpt --save predictions/t3n_label_other_cluster.pkl predictions/t3n_predict_other_cluster.pkl