#!/usr/bin/env bash
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/normal --label_option single --pan n --data_set_save static/trn_data_normal.pkl static/trn_label_normal.pkl static/trn_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/normal --label_option single --pan l --data_set_save static/trl_data_normal.pkl static/trl_label_normal.pkl static/trl_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/normal --label_option single --pan r --data_set_save static/trr_data_normal.pkl static/trr_label_normal.pkl static/trr_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/normal --label_option single --pan s --data_set_save static/trs_data_normal.pkl static/trs_label_normal.pkl static/trs_cluster_normal.pkl

python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/bass --label_option single --pan n --data_set_save static/trn_data_bass.pkl static/trn_label_bass.pkl static/trn_cluster_bass.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/drums --label_option single --pan n --data_set_save static/trn_data_drums.pkl static/trn_label_drums.pkl static/trn_cluster_drums.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/melody --label_option single --pan n --data_set_save static/trn_data_melody.pkl static/trn_label_melody.pkl static/trn_cluster_melody.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_train/other --label_option single --pan n --data_set_save static/trn_data_other.pkl static/trn_label_other.pkl static/trn_cluster_other.pkl


python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/normal --label_option multiple --pan n --data_set_save static/t1n_data_normal.pkl static/t1n_label_normal.pkl static/t1n_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/normal --label_option multiple --pan l --data_set_save static/t1l_data_normal.pkl static/t1l_label_normal.pkl static/t1l_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/normal --label_option multiple --pan r --data_set_save static/t1r_data_normal.pkl static/t1r_label_normal.pkl static/t1r_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/normal --label_option multiple --pan s --data_set_save static/t1s_data_normal.pkl static/t1s_label_normal.pkl static/t1s_cluster_normal.pkl

python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/bass --label_option multiple --pan n --data_set_save static/t1n_data_bass.pkl static/t1n_label_bass.pkl static/t1n_cluster_bass.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/drums --label_option multiple --pan n --data_set_save static/t1n_data_drums.pkl static/t1n_label_drums.pkl static/t1n_cluster_drums.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/melody --label_option multiple --pan n --data_set_save static/t1n_data_melody.pkl static/t1n_label_melody.pkl static/t1n_cluster_melody.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_1/other --label_option multiple --pan n --data_set_save static/t1n_data_other.pkl static/t1n_label_other.pkl static/t1n_cluster_other.pkl


python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/normal --label_option multiple --pan n --data_set_save static/t2n_data_normal.pkl static/t2n_label_normal.pkl static/t2n_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/normal --label_option multiple --pan l --data_set_save static/t2l_data_normal.pkl static/t2l_label_normal.pkl static/t2l_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/normal --label_option multiple --pan r --data_set_save static/t2r_data_normal.pkl static/t2r_label_normal.pkl static/t2r_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/normal --label_option multiple --pan s --data_set_save static/t2s_data_normal.pkl static/t2s_label_normal.pkl static/t2s_cluster_normal.pkl

python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/bass --label_option multiple --pan n --data_set_save static/t2n_data_bass.pkl static/t2n_label_bass.pkl static/t2n_cluster_bass.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/drums --label_option multiple --pan n --data_set_save static/t2n_data_drums.pkl static/t2n_label_drums.pkl static/t2n_cluster_drums.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/melody --label_option multiple --pan n --data_set_save static/t2n_data_melody.pkl static/t2n_label_melody.pkl static/t2n_cluster_melody.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_2/other --label_option multiple --pan n --data_set_save static/t2n_data_other.pkl static/t2n_label_other.pkl static/t2n_cluster_other.pkl


python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/normal --label_option multiple --pan n --data_set_save static/t3n_data_normal.pkl static/t3n_label_normal.pkl static/t3n_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/normal --label_option multiple --pan l --data_set_save static/t3l_data_normal.pkl static/t3l_label_normal.pkl static/t3l_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/normal --label_option multiple --pan r --data_set_save static/t3r_data_normal.pkl static/t3r_label_normal.pkl static/t3r_cluster_normal.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/normal --label_option multiple --pan s --data_set_save static/t3s_data_normal.pkl static/t3s_label_normal.pkl static/t3s_cluster_normal.pkl

python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/bass --label_option multiple --pan n --data_set_save static/t3n_data_bass.pkl static/t3n_label_bass.pkl static/t3n_cluster_bass.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/drums --label_option multiple --pan n --data_set_save static/t3n_data_drums.pkl static/t3n_label_drums.pkl static/t3n_cluster_drums.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/melody --label_option multiple --pan n --data_set_save static/t3n_data_melody.pkl static/t3n_label_melody.pkl static/t3n_cluster_melody.pkl
python3 data.py --strip_zeros True --scale True --segment_size 22050 --labels cel cla flu gac gel org pia sax tru vio none --data_set_dir IRMAS_test_3/other --label_option multiple --pan n --data_set_save static/t3n_data_other.pkl static/t3n_label_other.pkl static/t3n_cluster_other.pkl
